before_install:
  - gem install bundler

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.0

notifications:
  webhooks:
    urls:
      - https://hooker-arukoh.herokuapp.com/travis
    on_success: always
    on_failure: always
    on_start: false
